### ISSUE TITLE
Any scheduled plan to update the codes for Python 3?

### ISSUE THREAD

**Issue by jasonleongbio** [PacktPublishing/scikit-learn-Cookbook-Second-Edition#2]
Dear developers and authors,

First I really have to thank all of you for writing such a nice book for introducing the fundamental codes to use machine learning for predictive analysis. I've benefited a lot from following your recipes!

However, it seems that most codes were written either in Python 2.7 (e.g. the existence of the _print "xxx"_ syntax) or using older machine learning packages. Things have changed quite a lot in recent years, and as I proceed to later chapters in the book, a lot of the codes are either not supported any more, or there were some major updates in the fundamental syntax in Python 3 (esp. data types often became mis-matched in longer codes consisting of many functions). For example, in Chapter 9, many syntaxes involved in tree, GridSearchCV, best_estimator_ etc. seem to have updates in recent versions, and thus now it took me some time to google how to update the sample codes in the book in order to generate the same plot or analysis.

Therefore, may I know if the authors have any plan or intention to update the codes for a future version of the book? Thank you!

Best,
Jason.

**Comment by sohamap** [comment]
Hey @jpiggod , 

I wanted to inform you that, we won't be able to make any code changes at this stage. 
And with due respect to your query, regarding the new update of the code for a future version of book. 
I am not in the best position to respond to this.

But, we highly appreciate the time you took in highlighting this.
Thanks a lot for your feedback.

Take  Care!
Thanks!
